projeto/projetointegrador/forms/urls.py
from django.urls import path

from . import views

app_name = "forms"

urlpatterns = [
    path("", views.forms, name="forms"),
    path("forms/", views.cadastro, name="cadastro"),
]

projeto/projetointegrador/projetointegrador/urls.py
from django.contrib import admin
from django.urls import path
from forms import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path('forms/', include('forms.urls')),
    path("create_event/", views.create_event, name="create_event"),
    path('list_events/', views.list_events, name='list_events'),
    path('api/inscricao/validar/', views.validar_inscricao, name='validar_inscricao'),
    ]


projeto/projetointegrador/forms/models.py
from django.db import models

# Create your models here.
class Contato(models.Model):
    nome = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    cpf = models.CharField(max_length=14)

class Event(models.Model):
    name = models.CharField(max_length=100)  # Nome do evento
    description = models.TextField(blank=True, null=True)  # Descrição opcional
    date = models.DateField()  # Data do evento
    location = models.CharField(max_length=200)  # Local do evento

    def __str__(self):
        return self.name

class Participant(models.Model):
    nome = models.CharField(max_length=255, null=True)
    email = models.EmailField()
    cpf = models.CharField(max_length=11, null=True)
    qr_code_data = models.TextField(null=True)
    event =  models.ForeignKey(Event, on_delete=models.CASCADE, null=True)

projeto/projetointegrador/forms/admin.py
from django.contrib import admin

# Register your models here.

projeto/projetointegrador/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

projeto/projetointegrador/forms/tests.py
from django.test import TestCase

# Create your tests here.

projeto/projetointegrador/forms/views.py
from django.http import HttpResponse
from django.template import loader
import qrcode
import base64
from django.shortcuts import get_object_or_404, redirect, render
from io import BytesIO
from .models import Event, Participant
from django.http import JsonResponse
import json
from django.contrib import messages


def index(request):
    template = loader.get_template("index.html")
    return HttpResponse(template.render({}, request))

def forms(request):
    template = loader.get_template("formulario.html")
    eventos = Event.objects.all()
    return HttpResponse(template.render({'eventos': eventos}, request))

def cadastro(request):
    texto_qrcode = request.POST.get("cpf")
    img = qrcode.make(texto_qrcode)
    buffered = BytesIO()
    img.save(buffered, format="PNG")
    qr_img_bytes = base64.b64encode(buffered.getvalue()).decode("ascii")
    template = loader.get_template("formulario.html")
   
    if request.method == "POST":
        nome = request.POST.get("nome")
        email = request.POST.get("email")
        cpf = request.POST.get("cpf")
        event = request.POST.get("event")

        try:
            Participant.objects.create(nome=nome, email=email, cpf=cpf, qr_code_data=qr_img_bytes, event=Event.objects.get(id=event))
            messages.success(request, "Participante cadastrado com sucesso!")
        except Exception as e:
            messages.error(request, f"Erro ao cadastrar participante: {e}")

    return HttpResponse(template.render({"qrcode": qr_img_bytes}, request))



def create_event(request):
    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")
        date = request.POST.get("date")
        location = request.POST.get("location")

        try:
            Event.objects.create(name=name, description=description, date=date, location=location)
            messages.success(request, "Evento cadastrado com sucesso!")
        except Exception as e:
            messages.error(request, f"Erro ao cadastrar evento: {e}")

        return redirect ("create_event")

    return render(request, "create_event.html")

def list_events(request):
    eventos = Event.objects.all()  # Ou outra lógica para filtrar eventos
    return render(request, 'list_events.html', {'eventos': eventos})

def validar_inscricao(request):
    print(request)
    cpf = request.GET.get('qrcode')

    if cpf:
        try:
            participante = Participant.objects.get(cpf=cpf)
            return JsonResponse({
                'status': 'success',
                    'message': 'Participante encontrado!',
                    'nome': participante.nome,
                    'email': participante.email,
            })
        except Participant.DoesNotExist:
            return JsonResponse({
                'status': 'error',
                'message': 'Participante não encontrado',
            })
    return JsonResponse({
        'status': 'error',
        'message': ' Metodo inválido',
    })

        

projeto/projetointegrador/forms/templates/create_event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Evento</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #ffffff;
            padding: 20px 30px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 400px;
        }

        h1 {
            text-align: center;
            color: #333333;
        }

        form {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        input, textarea, button {
            font-size: 16px;
            padding: 10px;
            border: 1px solid #cccccc;
            border-radius: 5px;
            outline: none;
        }

        input:focus, textarea:focus {
            border-color: #e0448d;
            box-shadow: 0 0 5px rgba(233, 4, 92, 0.5);
        }

        textarea {
            resize: none;
        }

        button {
            background-color: #e0448d ;
            color: #ffffff;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #aa0954;
        }

        .success-message {
            background-color: #d4edda;
            color: #d1648e;
            padding: 10px;
            border: 1px solid #c3e6cb;
            border-radius: 5px;
            margin-top: 15px;
            text-align: center;
        }

        .error-message {
            background-color: #f8d7da;
            color: #d30a5e;
            padding: 10px;
            border: 1px solid #f5c6cb;
            border-radius: 5px;
            margin-top: 15px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Cadastrar Evento</h1>
        {% if messages %}
    {% for message in messages %}
        <div class="{{ message.tags }}-message">{{ message }}</div>
    {% endfor %}
{% endif %}

        <form method="POST" action="">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Nome do Evento" required>
            <textarea name="description" placeholder="Descrição do Evento (opcional)" rows="4"></textarea>
            <input type="date" name="date" required>
            <input type="text" name="location" placeholder="Local do Evento" required>
            <button type="submit">Cadastrar</button>
        </form>
    </div>
</body>
</html>

projeto/projetointegrador/forms/templates/formulario.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Bem-vindo a TechSecure</title>
        <link rel="stylesheet" href="/static/estilo.css" />
    </head>

    <body>
        <!-- Formulário de Inscrição -->
        <section class="subscription-section" id="subscription-form">
            <div class="container">
                <h2>Inscreva-se Agora!</h2>
                <p>Preencha seus dados abaixo:</p>
                <form
                    id="form-inscricao"
                    action="{% url 'forms:cadastro' %}"
                    method="POST"
                >
                    {% csrf_token %}
                    <input
                        type="hidden"
                        name="csrf_token"
                        value="exemplo_token_gerado_backend"
                    />
                    <label for="nome">Nome Completo:</label>
                    <input
                        type="text"
                        id="nome"
                        name="nome"
                        required
                        placeholder="Seu nome completo"
                        oninput="validateField(this)"
                    />
                    <label for="email">Email Principal:</label>
                    <input
                        type="email"
                        id="email"
                        name="email"
                        required
                        placeholder="Seu melhor e-mail"
                        oninput="validateField(this)"
                    />
                    <label for="cpf">CPF:</label>
                    <input
                        type="text"
                        id="cpf"
                        name="cpf"
                        placeholder="Digite seu CPF"
                        oninput="validateField(this)"
                    />
                    <div class="evento-container">
                    <label for="event">Evento</label>
                    <select name="event" id="event" class="custom-select">
                        {% for event in eventos %}
                        <option value="{{ event.id }}">{{ event.name }}</option>
                        {% endfor %}
                    </select>
                    </div>
                    <button type="submit" class="cta-button" id="submit-button">
                        Inscrever Agora
                    </button>
                    <div>
                        <img
                            src="data:image/png;base64,{{ qrcode }}"
                            alt="QR Code"
                        />
                        <div id="feedback" class="feedback">
                            {% if messages %} {% for message in messages %}
                            <p class="message {{ message.tags }}">
                                {{ message }}
                            </p>
                            {% endfor %} {% endif %}
                        </div>
                    </div>
                </form>
                <footer>
                    <p>
                        &copy; 2024 TechSecure. Todos os direitos
                        reservados.
                    </p>
                </footer>
                <!-- Área de Feedback de Inscrição -->
                <div
                    id="feedback"
                    class="feedback"
                    style="display: none"
                ></div>
            </div>
        </section>
    </body>
</html>

projeto/projetointegrador/forms/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta https-equiv="Content-Security-Policy" content="default-src *;" />
    <title>Bem-vindo a TechSecure</title>
    <link rel="stylesheet" href="{% static 'estilo.css' %}"/>
    <script src="{% static 'js/script.js' %}" defer></script>
  </head>

  <body>
    <!-- Navbar com "TechSecure" -->
    <header>
      <nav class="navbar">
        <div class="logo">
          <img src="{% static  'img/logo 2.png' %}" alt="Logo TechSecure" class="logo">
          <a href="#">TechSecure</a>
        </div>
        <div class="menu">
          <a href="#nossos-servicos">Serviços</a>
          <a href="#">Suporte</a>
          <a href="#planos">Ofertas</a>
          <a href="#contato">Contato</a>
        </div>
      </nav>
    </header>

    <!-- Banner Principal -->
    <section class="banner">
      <div class="banner-content">
        <h1>Quem somos?</h1>
        <p>
          Somos uma empresa de segurança de controle de acesso. A TechSecure
          utiliza tecnologia de ponta para garantir a máxima segurança do seu
          acesso, para proteger sua conta, realizamos a autenticação através de
          QR Code.
        </p>
        <div class="botao-container">
          <a href="/forms" class="cta-button" onclick="scrollToForm()">Inscreva-se em evento</a>
          <a href="create_event" class="cta-button">Cadastrar evento</a>
          <button type="button" onclick="abrirCamera()" class="cta-button">Escanear QRCode</button>
          <a href="list_events" class="cta-button">Eventos Disponíveis</a>
        </div>
    </section>

    <div id="reader" width="600px"></div>

    <section class="products" id="nossos-servicos">
      <h2>Nossos serviços</h2>
      <div class="product-cards">
        <div class="product-card">
          <img src="{% static  'img/card1.jpg' %}" alt="Produto 1" />
          <h3>Autenticação Segura para Acesso</h3>
          <p> Implementamos um sistema de autenticação segura que utiliza um leitor de QR Code para garantir um acesso rápido e protegido.</p>
          <button onclick="scrollToPlans()">Ver Detalhes</button>
        </div>
        <div class="product-card">
          <img src="{% static  'img/card2.jpg' %}" alt="Produto 2" />
          <h3>Treinamento da Equipe de Segurança</h3>
          <p>Oferecemos treinamentos especializados para sua equipe de segurança, garantindo o uso eficiente do nosso sistema e a manutenção das melhores práticas de segurança.</p>
          <button onclick="scrollToPlans()">Ver Detalhes</button>
        </div>
        <div class="product-card">
          <img src="{% static  'img/card3.jpg' %}" alt="Produto 3" />
          <h3> Geração de relatórios de Entradas e Saídas</h3>
          <p> Acompanhamento em tempo real das entradas e saídas, com relatórios detalhados para garantir total controle e segurança sobre o fluxo de acessos.</p>
          <button  onclick="scrollToPlans()">Ver Detalhes</button>
        </div>
      </div>
    </section>
      <section class="pricing" id="planos">
        <h2>Planos Disponíveis</h2>
        <div class="pricing-cards">
          <div class="pricing-card">
            <h3>Básico</h3>
            <p>Ideal para pequenas empresas.</p>
            <p class="price">R$99/mês</p>
            <button>Assinar</button>
          </div>
          <div class="pricing-card">
            <h3>Intermediário</h3>
            <p>Para empresas em crescimento.</p>
            <p class="price">R$199/mês</p>
            <button>Assinar</button>
          </div>
          <div class="pricing-card">
            <h3>Premium</h3>
            <p>O melhor para grandes corporações.</p>
            <p class="price">R$299/mês</p>
            <button>Assinar</button>
          </div>
        </div>
      </section>
      <section class="qrcode-events">
        <h2>Por que usar QR Codes para Controle de Acesso em Eventos?</h2>
      
        <h3>1. Entrada Rápida e Sem Filas</h3>
        <p>
          O QR Code permite que os participantes acessem o evento rapidamente, sem a necessidade de bilhetes físicos. Com um simples escaneamento, a entrada é liberada de forma instantânea.
        </p>
      
        <h3>2. Aumenta a Segurança</h3>
        <p>
          Utilizar QR Codes garante que apenas pessoas autorizadas tenham acesso, já que o código é único e gerado dinamicamente, dificultando fraudes e falsificações.
        </p>
      
        <h3>3. Redução de Custos</h3>
        <p>
          Com o QR Code, não há necessidade de imprimir ingressos físicos ou utilizar sistemas caros, o que reduz significativamente os custos operacionais.
        </p>
      
        <h3>4. Melhora a Experiência do Participante</h3>
        <p>
          O processo de entrada é ágil e digital, proporcionando uma experiência mais moderna e conveniente para os participantes.
        </p>
      </section>
      
      <section class="contact" id="contato">
        <h2>Entre em Contato</h2>
          <p>
            Se você tiver dúvidas ou precisar de mais informações, entre em contato conosco através de qualquer um dos canais abaixo. Estamos aqui para ajudar!
          </p>
          <div class="contact-details">
            <div class="contact-item">
              <h3>Email</h3>
              <p><a href="#">contato@techsecureeventos.com.br</a></p>
            </div>
            
            <div class="contact-item">
              <h3>Telefone</h3>
              <p>(84) 3301-1401</p>
            </div>
        
            <div class="contact-item">
              <h3>Endereço Matriz</h3>
              <p> Avenida Rui Barbosa, n° 1270, Lagoa Nova, Natal-RN</p>
            </div>
        
            <div class="contact-item">
              <h3>Redes Sociais</h3>
              <p>
                <a href="https://www.facebook.com/TechSecure" target="_blank">Facebook</a> | 
                <a href="https://www.instagram.com/TechSecure" target="_blank">Instagram</a> |
                <a href="https://www.linkedin.com/company/TechSecure" target="_blank">LinkedIn</a>
              </p>
            </div>
          </div>

      <!-- Rodapé -->
    <footer>
      <p>&copy; 2024 TechSecure. Todos os direitos reservados.</p>
      <div>
        <a href="#">Termos de Uso</a>
        <a href="#">Política de Privacidade</a>
        <a href="#">Ajuda</a>
      </div>
    </footer>
  </body>

  <script type="text/javascript" src="{% static 'scripts.js' %}"></script>
  <script type="text/javascript" src="{% static 'html5-qrcode.min.js' %}"></script>
</html>

projeto/projetointegrador/forms/templates/list_events.html
<link rel="stylesheet" href="/static/estilo.css" />

<h1 class="eventos-titulo">Eventos Disponíveis</h1>
<ul class="eventos-lista">
    {% for event in eventos %}
    <li>
        <strong>{{ event.name }}</strong><br />
        <p>Data: {{ event.date }}</p>
        <p>Local: {{ event.location }}</p>
    </li>
    <hr />
    {% endfor %}
</ul>

projeto/projetointegrador/templates/home.html
<h1>Olá mundo</h1>
<button>clique aqui</button>
<hr>